/* 
        if (true){
            var x = 3;
        }
        console.log(x);  //anonymous 함수 이내
        if (true){
            const y = 3;
            let z = 3;
        }
        console.log(y); //if 블록 내 변수 사용 시도 = 에러
        console.log(z); //동일하게 에러 */

        /* const a = 0;
        a = 1;
        let b = 0
        b = 1; */

    const num3 = 1;
    const num4 = 2;
    const res = 3;
    console.log(`${num3} 더하기 ${num4} 는 '${res}' 입니다.`)